/* Bleed Blue international portal. All statistics come from the bundled source archive. */
(() => {
'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = n => n == null ? '—' : Number(n).toLocaleString('en-IN');
const overs = n => `${Math.floor(n / 6)}.${n % 6}`;
const date = d => new Date(d + 'T12:00:00').toLocaleDateString('en-GB', {day:'numeric',month:'short',year:'numeric'});
const params = new URLSearchParams(location.search);
const aliases = {'V Kohli':'Virat Kohli','RG Sharma':'Rohit Sharma','SR Tendulkar':'Sachin Tendulkar','JJ Bumrah':'Jasprit Bumrah','R Ashwin':'Ravichandran Ashwin','RA Jadeja':'Ravindra Jadeja','SC Ganguly':'Sourav Ganguly','MS Dhoni':'MS Dhoni','KL Rahul':'KL Rahul','Yuvraj Singh':'Yuvraj Singh','V Sehwag':'Virender Sehwag','S Dhawan':'Shikhar Dhawan','RR Pant':'Rishabh Pant','HH Pandya':'Hardik Pandya','A Kumble':'Anil Kumble','R Dravid':'Rahul Dravid','AB de Villiers':'AB de Villiers','SPD Smith':'Steve Smith','JE Root':'Joe Root','KS Williamson':'Kane Williamson','JC Buttler':'Jos Buttler','JM Anderson':'James Anderson','SCJ Broad':'Stuart Broad','DA Warner':'David Warner','BA Stokes':'Ben Stokes','SS Mandhana':'Smriti Mandhana','EA Perry':'Ellyse Perry','AE Gardner':'Ashleigh Gardner','BL Mooney':'Beth Mooney','MM Lanning':'Meg Lanning','AC Kerr':'Amelia Kerr','SFM Devine':'Sophie Devine','H Kaur':'Harmanpreet Kaur'};
const fullname = n => aliases[n] || n;
const playerUrl = p => '/players/?id=' + encodeURIComponent(p.id);
const matchUrl = m => '/international/?match=' + encodeURIComponent(m.id);
const code = name => ({'South Africa':'SA','New Zealand':'NZ','Sri Lanka':'SL','West Indies':'WI','United Arab Emirates':'UAE','United States of America':'USA'}[name] || name.slice(0,3).toUpperCase());
let D, images = {}, page = 0;
const pageSize = 24;
async function json(url) { const response = await fetch(url); if(!response.ok) throw new Error(`Unable to load archive (${response.status}).`); return response.json(); }
function photo(p, className='') {
 const file = images[fullname(p.name)] || images[p.name];
 return file ? `<img class="${className}" src="/images/players/${esc(file)}" alt="${esc(fullname(p.name))}" loading="lazy">` : `<span class="no-photo ${className}" aria-hidden="true">${esc(fullname(p.name).split(' ').filter(Boolean).map(n=>n[0]).slice(0,2).join(''))}</span>`;
}
function stats(p, fmt='all') {
 const all = fmt === 'all' ? Object.values(p.formats) : [p.formats[fmt]].filter(Boolean);
 if (!all.length) return null;
 const s = {}; all.forEach(row=>Object.entries(row).forEach(([k,v])=>s[k] = k === 'highest' ? Math.max(s[k] || 0,v) : (s[k] || 0)+v));
 return {...s,avg:s.outs ? (s.runs/s.outs).toFixed(2):null,sr:s.balls?(s.runs/s.balls*100).toFixed(2):null,econ:s.legal?(s.conceded/s.legal*6).toFixed(2):null,bowlAvg:s.wickets?(s.conceded/s.wickets).toFixed(2):null};
}
function result(m) {
 const o=m.outcome;
 if(o.winner) { const margin=Object.entries(o.by || {}).map(([k,v])=>k==='innings'&&v===1?'an innings':`${v} ${v===1&&k!=='innings'?k.replace(/s$/,''):k}`).join(' and '); return `${o.winner} won${margin?' by '+margin:''}${o.method?' ('+o.method+')':''}`; }
 if(o.eliminator) return `${o.eliminator} won the eliminator`;
 if(o.bowl_out) return `${o.bowl_out} won the bowl-out`;
 return ({tie:'Match tied',draw:'Match drawn','no result':'No result'}[o.result] || 'Result not recorded');
}
function total(m, team) { return m.totals.filter(t=>t.team===team&&!t.super_over).map(t=>`${t.runs}/${t.wickets}`).join(' & ') || '—'; }
function scoreCard(m) { return `<a class="score-card" href="${matchUrl(m)}"><div class="score-meta"><b>${esc(m.format)} · ${esc(m.gender.toUpperCase())}</b><span>${date(m.date)}</span></div>${m.teams.map(t=>`<div class="team-row"><span class="team-code">${esc(code(t))}</span><span>${esc(t)}</span><strong>${total(m,t)}</strong></div>`).join('')}<p class="score-result">${esc(result(m))}</p></a>`; }
function playerCard(p, sort='runs', fmt='all') { const s=stats(p,fmt); return `<a class="player-card" href="${playerUrl(p)}"><div class="player-image">${photo(p)}</div><div class="player-info"><h3>${esc(fullname(p.name))}</h3><p>${esc(p.teams.join(' / '))} · ${esc(p.gender)}</p><strong>${num(s?.[sort] || 0)}</strong><small>${sort==='wickets'?'WICKETS':sort==='matches'?'APPEARANCES':'RUNS'} IN ARCHIVE</small></div></a>`; }
function options(values, chosen='all') { return values.map(v=>`<option value="${esc(v)}" ${v===chosen?'selected':''}>${esc(v)}</option>`).join(''); }
function saveCsv(rows,name) {const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.textContent='Save CSV ('+num(rows.length-1)+' rows) ↓';a.className='text-link';const notice=document.createElement('p');notice.className='export-notice';notice.setAttribute('role','status');notice.append('Your export is ready. ',a);document.querySelector('.export-notice')?.remove();document.querySelector('.directory-tools')?.after(notice);a.click();}
function pagination(count, render) {const pages=Math.max(1,Math.ceil(count/pageSize));$('#pager').innerHTML=`<button id="prev" ${page===0?'disabled':''}>← Previous</button><span>${count?`${page+1} / ${pages}`:'No results'}</span><button id="next" ${page>=pages-1?'disabled':''}>Next →</button>`;$('#prev').onclick=()=>{page--;render();};$('#next').onclick=()=>{page++;render();};}
function showError(error) { const root=$('#portalContent')||$('#recentMatches'); root.innerHTML=`<div class="error-box" role="alert">${esc(error.message)} <button onclick="location.reload()">Retry</button></div>`; }
function home() {
 $('#metrics').innerHTML=[[num(D.meta.matches),'Matches in the archive'],[num(D.meta.players),'Player profiles'],['3','International formats'],[num(D.meta.teams.length),'International teams']].map(([n,t])=>`<div><strong>${n}</strong><span>${t}</span></div>`).join('');
 const renderRecent = fmt=>$('#recentMatches').innerHTML=D.matches.filter(m=>fmt==='all'||m.format===(fmt==='T20'?'T20I':fmt)).slice(0,4).map(scoreCard).join('');renderRecent('all');
 $('#matchTabs').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$('#matchTabs').querySelectorAll('button').forEach(t=>{t.classList.toggle('selected',t===b);t.setAttribute('aria-pressed',String(t===b));});renderRecent(b.dataset.format);});
 $('#formatCards').innerHTML=[['Test','The ultimate examination','test'],['ODI','Fifty overs. Endless possibilities.','odi'],['T20I','Every ball changes the game.','t20']].map(([fmt,desc,cls])=>{const summary=D.format_summary[fmt], count=summary.matches, women=summary.women;return `<a class="format-card ${cls}" href="/international/?format=${fmt}"><h3>${fmt==='Test'?'Test cricket':fmt+' cricket'}</h3><p class="format-desc">${desc}</p><div class="format-values"><div><strong>${num(count)}</strong><span>Matches</span></div><div><strong>${num(summary.teams)}</strong><span>Teams</span></div></div><div class="win-meter"><i style="width:${women/count*100}%"></i></div><div class="win-label"><span>Men ${num(count-women)}</span><span>Women ${num(women)}</span></div></a>`;}).join('');
 $('#archiveDate').textContent=`Available source matches: ${date(D.meta.first)} – ${date(D.meta.last)} · Men & women · Archive totals, not complete career records.`;
 const featured=['V Kohli','RG Sharma','JJ Bumrah','MS Dhoni'].map(n=>D.players.find(p=>p.name===n)).filter(Boolean);$('#featuredPlayers').innerHTML=featured.map(p=>playerCard(p,p.name==='JJ Bumrah'?'wickets':'runs')).join('');
 const leaders=[...D.players].sort((a,b)=>stats(b).runs-stats(a).runs).slice(0,5);$('#leaders').innerHTML=leaders.map((p,i)=>`<a class="leader" href="${playerUrl(p)}"><span class="leader-rank">0${i+1}</span>${photo(p)}<div class="leader-name">${esc(fullname(p.name))}<small>${esc(p.teams[0])}</small></div><strong>${num(stats(p).runs)}</strong></a>`).join('');
}
function directory() {
 if(params.has('id')) {profile(params.get('id'));return;}
 $('#portalContent').innerHTML=`<div class="directory-tools"><input id="playerQuery" aria-label="Search players" placeholder="Search player or country…"><select id="playerGender" aria-label="Player gender"><option value="all">Men & women</option>${options(['Men','Women'])}</select><select id="playerFormat" aria-label="Player format"><option value="all">All formats</option>${options(['Test','ODI','T20I'])}</select><select id="playerSort" aria-label="Sort players">${options(['runs','wickets','matches'],params.get('sort')||'runs')}</select><a class="text-link" href="#compare">Compare players ↓</a></div><p id="playerCount" class="directory-count"></p><div id="playerResults" class="directory-grid"></div><div id="pager" class="pagination"></div><section id="compare" class="compare-section"><div class="eyebrow">SIDE BY SIDE</div><h2>Let the numbers do the talking.</h2><p class="compare-note">Compare players within the available ball-by-ball archive. Missing formats show a dash. Figures are not complete career totals.</p><div class="compare-controls"><select id="compareA" aria-label="First player"></select><span>vs</span><select id="compareB" aria-label="Second player"></select><select id="compareFormat" aria-label="Comparison format"><option value="all">All formats</option>${options(['Test','ODI','T20I'])}</select></div><div id="comparison"></div></section>`;
 const render=()=>{const query=$('#playerQuery').value.toLowerCase().trim(),gender=$('#playerGender').value,fmt=$('#playerFormat').value,sort=$('#playerSort').value;const players=D.players.filter(p=>(gender==='all'||p.gender===gender)&&(fmt==='all'||p.formats[fmt])&&`${p.name} ${fullname(p.name)} ${p.teams.join(' ')}`.toLowerCase().includes(query)).sort((a,b)=>(stats(b,fmt)?.[sort]||0)-(stats(a,fmt)?.[sort]||0));$('#playerCount').textContent=`${num(players.length)} players · ranked by archive ${sort}`;$('#playerResults').innerHTML=players.slice(page*pageSize,(page+1)*pageSize).map(p=>playerCard(p,sort,fmt)).join('')||'<p>No players match these filters. Try another name or format.</p>';pagination(players.length,render);};
 ['playerQuery','playerGender','playerFormat','playerSort'].forEach(id=>$('#'+id).addEventListener(id==='playerQuery'?'input':'change',()=>{page=0;render();}));render();
 const playerOptions=[...D.players].sort((a,b)=>fullname(a.name).localeCompare(fullname(b.name))).map(p=>`<option value="${esc(p.id)}">${esc(fullname(p.name))} · ${esc(p.teams[0])} · ${p.gender}</option>`).join('');$('#compareA').innerHTML=playerOptions;$('#compareB').innerHTML=playerOptions;
 $('#compareA').value=D.players.find(p=>p.name==='V Kohli')?.id||D.players[0].id;$('#compareB').value=D.players.find(p=>p.name==='RG Sharma')?.id||D.players[1].id;
 const compare=()=>{const a=D.players.find(p=>p.id===$('#compareA').value),b=D.players.find(p=>p.id===$('#compareB').value),fmt=$('#compareFormat').value,sa=stats(a,fmt),sb=stats(b,fmt);const measures=[['matches','Matches'],['innings','Batting innings'],['runs','Runs'],['avg','Batting average'],['sr','Strike rate'],['highest','Highest score'],['hundreds','Centuries'],['fifties','Half-centuries'],['wickets','Wickets'],['bowlAvg','Bowling average',true],['econ','Economy',true],['catches','Catches'],['stumpings','Stumpings']];$('#comparison').innerHTML=`<table class="compare-table"><thead><tr><th>${esc(fullname(a.name))}</th><th>${esc(fmt==='all'?'All formats':fmt)}</th><th>${esc(fullname(b.name))}</th></tr></thead><tbody>${measures.map(([key,label,lower])=>{const va=sa?.[key],vb=sb?.[key],valid=va!=null&&vb!=null;return `<tr><td class="${valid&&(lower?+va<+vb:+va>+vb)?'best':''}">${va??'—'}</td><th scope="row">${label}</th><td class="${valid&&(lower?+vb<+va:+vb>+va)?'best':''}">${vb??'—'}</td></tr>`;}).join('')}</tbody></table>`;};['compareA','compareB','compareFormat'].forEach(id=>$('#'+id).onchange=compare);compare();if(location.hash==='#compare')$('#compare').scrollIntoView();
}
function profile(id) {
 const p=D.players.find(p=>p.id===id);if(!p){$('#portalContent').innerHTML='<p>Player not found. <a href="/players/">Browse all players</a></p>';return;}
 document.title=fullname(p.name)+' — Player profile | Bleed Blue';$('.directory-head h1').textContent=fullname(p.name);$('.directory-head p').textContent=p.teams.join(' / ')+' · '+p.gender+' · Archive appearances '+date(p.first)+' – '+date(p.last);
 $('#portalContent').innerHTML=`<a class="text-link" href="/players/">← All players</a><div class="profile-layout"><div class="profile-portrait">${photo(p)}</div><section class="rail-card"><div class="eyebrow">ARCHIVE CAREER STATISTICS</div><div class="directory-tools"><label for="profileFormat">Format</label><select id="profileFormat"><option value="all">All formats</option>${options(Object.keys(p.formats))}</select><a class="text-link" href="/players/#compare">Compare players ↗</a></div><div id="profileStats" class="profile-stats"></div><p class="data-caption">Based on matches available in this archive. Not complete career statistics.</p></section></div><section class="feature-section"><div class="section-top"><h2>Recent appearances</h2></div><div class="archive-match-grid" id="appearances"></div></section>`;
 const render=()=>{const s=stats(p,$('#profileFormat').value);$('#profileStats').innerHTML=[['Matches',num(s.matches)],['Runs',num(s.runs)],['Average',s.avg??'—'],['Strike rate',s.sr??'—'],['Centuries',s.hundreds],['Wickets',num(s.wickets)],['Bowling avg.',s.bowlAvg??'—'],['Economy',s.econ??'—']].map(([k,v])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('');};$('#profileFormat').onchange=render;render();
 // The compact match index carries playing-XI IDs, so appearances never guess from country alone.
 const recent=D.matches.filter(m=>m.player_ids?.includes(id)).slice(0,12);$('#appearances').innerHTML=recent.map(scoreCard).join('')||'<p class="data-caption">No appearance index is available for this profile.</p>';
}
function international() {
 const params = new URLSearchParams(location.search);
 if(params.has('match')){return matchDetail(params.get('match'));}
 const view=location.hash.replace('#','')||'matches';
 if(view==='coverage'){coverage();return;}
 $('#portalContent').innerHTML=`<nav class="archive-tabs" aria-label="Archive sections">${[['matches','Matches'],['series','Series'],['teams','Teams'],['venues','Venues'],['records','Records'],['coverage','Coverage']].map(([key,label])=>`<a href="#${key}" ${key===view?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="directory-tools"><input id="matchQuery" aria-label="Search international matches" placeholder="Search team, venue, series or date…" value="${esc(params.get('q')||'')}"><select id="matchGender" aria-label="Match gender"><option value="all">Men & women</option>${options(['Men','Women'],params.get('gender'))}</select><select id="intlFormat" aria-label="International format"><option value="all">All formats</option>${options(['Test','ODI','T20I'],params.get('format')||'all')}</select><select id="intlTeam" aria-label="International team"><option value="all">All teams</option>${options(D.meta.teams,params.get('team')||'all')}</select><select id="intlYear" aria-label="Match year"><option value="all">All years</option>${options([...new Set(D.matches.map(m=>m.date.slice(0,4)))],params.get('year'))}</select><button id="exportMatches" class="primary-button">Export CSV ↓</button><button id="resetFilters" class="reset-button">Reset filters</button></div><div id="searchPlayerResults"></div><p id="matchCount" class="directory-count"></p><div id="matchResults"></div><div id="pager" class="pagination"></div>`;
 let filtered=[];
 const render=()=>{const q=$('#matchQuery').value.toLowerCase().trim(),gender=$('#matchGender').value,fmt=$('#intlFormat').value,team=$('#intlTeam').value,year=$('#intlYear').value;
 const foundPlayers=q.length>=2?D.players.filter(p=>`${p.name} ${fullname(p.name)}`.toLowerCase().includes(q)&&(gender==='all'||p.gender===gender)&&(fmt==='all'||p.formats[fmt])&&(team==='all'||p.teams.includes(team))):[];
 const playerIds=new Set(foundPlayers.map(p=>p.id));
 $('#searchPlayerResults').innerHTML=foundPlayers.length?`<section class="feature-section"><h2>Players matching your search</h2><div class="player-grid search-players">${foundPlayers.slice(0,8).map(p=>playerCard(p,'runs',fmt)).join('')}</div></section>`:'';
 filtered=D.matches.filter(m=>(gender==='all'||m.gender===gender)&&(fmt==='all'||m.format===fmt)&&(team==='all'||m.teams.includes(team))&&(year==='all'||m.date.startsWith(year))&&(`${m.teams.join(' ')} ${m.venue} ${m.event} ${m.date} ${m.city}`.toLowerCase().includes(q)||m.player_ids?.some(id=>playerIds.has(id))));
 const nextUrl=new URL(location.href);for(const [key,value] of Object.entries({q,gender,format:fmt,team,year})){if(value&&value!=='all')nextUrl.searchParams.set(key,value);else nextUrl.searchParams.delete(key);}history.replaceState(null,'',nextUrl.pathname+nextUrl.search+nextUrl.hash);
 $('#matchCount').textContent=`${num(filtered.length)} matches · Available archive ${date(D.meta.first)} – ${date(D.meta.last)}`;
 if(['teams','venues','series'].includes(view)){const groups=new Map();filtered.forEach(m=>{if(view==='series'&&!m.event)return;const keys=view==='teams'?m.teams:[view==='venues'?m.venue:m.event||'Unspecified series'];keys.forEach(name=>{const group=groups.get(name)||{name,played:0,wins:0,last:m.date};group.played++;group.wins+=m.outcome.winner===name;groups.set(name,group);});});const items=[...groups.values()].sort((a,b)=>b.played-a.played);$('#matchResults').className='explore-grid';$('#matchResults').innerHTML=items.slice(page*pageSize,(page+1)*pageSize).map(g=>`<a href="/international/?${view==='teams'?'team':'q'}=${encodeURIComponent(g.name==='Unspecified series'?'':g.name)}"><h3>${esc(g.name)}</h3><p>${num(g.played)} archive matches${view==='teams'?' · '+num(g.wins)+' wins':''}<br>Latest: ${date(g.last)}</p><span class="text-link">Browse matches →</span></a>`).join('')||'<p>No results. Try changing the filters.</p>';pagination(items.length,render);}
 else if(view==='records'){const totals=filtered.flatMap(m=>m.totals.filter(t=>!t.super_over).map(t=>({...t,match:m}))).sort((a,b)=>b.runs-a.runs);$('#matchResults').className='table-container';$('#matchResults').innerHTML=`<h2>Highest innings totals in the selected archive</h2><p class="data-caption">Use the format and gender filters for like-for-like records.</p><table class="compare-table"><thead><tr><th>Team</th><th>Score</th><th>Opponent</th><th>Format</th><th>Date</th></tr></thead><tbody>${totals.slice(page*pageSize,(page+1)*pageSize).map(t=>`<tr><td><a href="${matchUrl(t.match)}">${esc(t.team)} ↗</a></td><td><strong>${t.runs}/${t.wickets}</strong></td><td>${esc(t.match.teams.find(x=>x!==t.team))}</td><td>${t.match.format} · ${t.match.gender}</td><td>${date(t.match.date)}</td></tr>`).join('')}</tbody></table>`;pagination(totals.length,render);}
 else {$('#matchResults').className='archive-match-grid';$('#matchResults').innerHTML=filtered.slice(page*pageSize,(page+1)*pageSize).map(scoreCard).join('')||'<p>No matches found. Clear the search or change the filters.</p>';pagination(filtered.length,render);}
 };
 ['matchQuery','matchGender','intlFormat','intlTeam','intlYear'].forEach(id=>$('#'+id).addEventListener(id==='matchQuery'?'input':'change',()=>{page=0;render();}));$('#resetFilters').onclick=()=>{['matchGender','intlFormat','intlTeam','intlYear'].forEach(id=>$('#'+id).value='all');$('#matchQuery').value='';page=0;render();};$('#exportMatches').onclick=()=>saveCsv([['Date','Format','Gender','Team 1','Team 2','Venue','Result','Source'],...filtered.map(m=>[m.date,m.format,m.gender,...m.teams,m.venue,result(m),'Cricsheet'])],'bleed-blue-matches');render();
}
function coverage() {$('#portalContent').innerHTML=`<a class="text-link" href="/international/">← Match centre</a><section class="compare-section"><div class="eyebrow">TRANSPARENT BY DESIGN</div><h2>What this archive includes</h2><div class="profile-stats">${[[num(D.meta.matches),'Source matches'],[num(D.meta.players),'Players'],[num(D.meta.gender.Men),"Men’s matches"],[num(D.meta.gender.Women),"Women’s matches"]].map(([v,k])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('')}</div><p>Imported ${date(D.meta.generated.slice(0,10))}. Available match dates: ${date(D.meta.first)} to ${date(D.meta.last)}.</p><p>All available Cricsheet men’s and women’s international Test, ODI and T20I files are included. International teams beyond the Full Members are included where source data exists. IPL and other domestic competitions are excluded.</p><h3>Coverage is not complete cricket history</h3><p>Historical matches without public ball-by-ball data are absent. Cricsheet also withholds matches involving Afghanistan. Statistics shown here are calculated from available deliveries and may differ from complete career records. A match’s source file can itself have incomplete innings; only supplied deliveries are counted. Super overs are shown on scorecards and excluded from player career aggregates.</p><h3>Live scores and fixtures</h3><p>This is a results and statistics archive. It does not supply live scores, future fixtures, rankings or news. Match dates are shown throughout so archived results are clearly identified.</p><h3>Sources & attribution</h3><p><a class="text-link" href="https://cricsheet.org/">Cricsheet</a> supplies the ball-by-ball data. Scorecards and statistics are derived from these files. Player images use the existing Wikimedia-sourced photo collection; players without supplied images have initials.</p><p>The <a class="text-link" href="/overview/">India hub</a> preserves the original curated career snapshots and recovered match catalog, with separate dates and coverage. Those older records have not been independently reverified by this import.</p><a class="primary-button" href="/data/manifest.json" download>Download data manifest ↓</a><p class="data-caption">Independent project. Not affiliated with ICC or any national cricket board.</p></section>`;}
async function matchDetail(id) {
 const m=D.matches.find(m=>m.id===id);if(!m){$('#portalContent').innerHTML='<p>Match not found. <a href="/international/">Browse matches</a></p>';return;}
 $('.directory-head h1').textContent=m.teams.join(' vs ');$('.directory-head p').textContent=`${date(m.date)} · ${m.format} · ${m.gender} · ${m.venue}`;document.title=m.teams.join(' vs ')+' — Scorecard | Bleed Blue';
 const shard=await json('/data/scorecards/'+encodeURIComponent(m.shard)+'.json'),detail=shard[id];
 $('#portalContent').innerHTML=`<a class="text-link" href="/international/">← Match centre</a><section class="match-summary"><div class="eyebrow light">${esc(m.event||'INTERNATIONAL CRICKET')}</div>${m.teams.map(t=>`<div class="match-team"><span>${esc(t)}</span><strong>${total(m,t)}</strong></div>`).join('')}<h2>${esc(result(m))}</h2><p>${detail.toss.winner?'Toss: '+esc(detail.toss.winner)+' chose to '+esc(detail.toss.decision):'Toss not recorded'}${detail.awards.length?' · Player of the match: '+detail.awards.map(fullname).map(esc).join(', '):''}</p></section><div class="innings-tabs segmented" id="inningsTabs" aria-label="Select innings">${detail.innings.map((inn,i)=>`<button data-inning="${i}" aria-pressed="${i===0}" class="${i===0?'selected':''}">${esc(inn.team)} · Inn ${i+1}${inn.super_over?' (Super over)':''}</button>`).join('')}</div><div id="inningsContent"></div><section class="compare-section"><h2>Playing XIs</h2><div class="xi-columns">${Object.entries(detail.players).map(([team,players])=>`<div><h3>${esc(team)}</h3>${players.map(p=>`<a class="xi-player" href="${playerUrl(p)}">${esc(fullname(p.name))} ↗</a>`).join('')}</div>`).join('')}</div><p class="data-caption">Derived from <a class="text-link" href="${esc(detail.source)}">Cricsheet source data</a>. Scores reflect supplied deliveries. No invented commentary.</p></section>`;
 const render=i=>{const inn=detail.innings[i];if(!inn){$('#inningsContent').innerHTML='<p>No innings data in this source match.</p>';return;}const max=Math.max(1,...inn.overs.map(o=>o.runs));$('#inningsContent').innerHTML=`<section class="compare-section"><div class="section-top"><h2>${esc(inn.team)} <span class="blue">${inn.runs}/${inn.wickets}${inn.declared?'d':''}</span></h2><span>${overs(inn.balls)} overs · Extras ${inn.extras}</span></div><div class="table-container"><table class="score-table"><thead><tr><th>Batter</th><th>Dismissal</th><th>R</th><th>B</th><th>4s</th><th>6s</th><th>SR</th></tr></thead><tbody>${inn.batting.map(b=>`<tr><td><a href="${playerUrl(b)}">${esc(fullname(b.name))}</a></td><td class="dismissal">${esc(b.dismissal)}</td><td><strong>${b.runs}${b.out?'':'*'}</strong></td><td>${b.balls}</td><td>${b.fours}</td><td>${b.sixes}</td><td>${b.balls?(b.runs/b.balls*100).toFixed(2):'—'}</td></tr>`).join('')}</tbody></table></div><h3>Bowling</h3><div class="table-container"><table class="score-table"><thead><tr><th>Bowler</th><th>O</th><th>R</th><th>W</th><th>Econ</th></tr></thead><tbody>${inn.bowling.map(b=>`<tr><td><a href="${playerUrl(b)}">${esc(fullname(b.name))}</a></td><td>${overs(b.balls)}</td><td>${b.runs}</td><td><strong>${b.wickets}</strong></td><td>${b.balls?(b.runs/b.balls*6).toFixed(2):'—'}</td></tr>`).join('')}</tbody></table></div></section><section class="compare-section"><div class="section-top"><h2>Runs by over</h2><span class="data-caption">Orange marks an over with a wicket</span></div><div class="over-chart" role="img" aria-label="Runs scored in each over. Orange bars indicate wickets.">${inn.overs.map(o=>`<div class="over-bar-wrap" title="Over ${o.over}: ${o.runs} runs, ${o.wickets} wickets, total ${o.total}"><div class="over-bar ${o.wickets?'wicket':''}" style="height:${Math.max(2,o.runs/max*100)}%"></div><small>${o.over}</small></div>`).join('')}</div><details><summary>View over-by-over data</summary><div class="table-container"><table class="score-table"><thead><tr><th>Over</th><th>Runs</th><th>Wickets</th><th>Total</th></tr></thead><tbody>${inn.overs.map(o=>`<tr><td>${o.over}</td><td>${o.runs}</td><td>${o.wickets}</td><td>${o.total}</td></tr>`).join('')}</tbody></table></div></details><h3>Fall of wickets</h3><p class="compare-note">${inn.fall.map(w=>`${w.runs}/${w.wicket} (${esc(fullname(w.player))}, ${overs(w.balls)} ov)`).join(' · ')||'No wickets recorded.'}</p></section>`;};$('#inningsTabs').onclick=e=>{const b=e.target.closest('button');if(!b)return;$('#inningsTabs').querySelectorAll('button').forEach(t=>{t.classList.toggle('selected',t===b);t.setAttribute('aria-pressed',String(t===b));});render(Number(b.dataset.inning));};render(0);
}
function activeNavigation() {
 const active=document.body.dataset.page==='players'?'/players/':document.body.dataset.page==='international'?(location.hash==='#series'?'/international/#series':location.hash==='#records'?'/international/#records':'/international/'):'/';
 document.querySelectorAll('#navigation a').forEach(a=>{if(a.getAttribute('href')===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
}
activeNavigation();window.addEventListener('hashchange',activeNavigation);
$('.menu-button')?.addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('.menu-button').setAttribute('aria-expanded',String(open));});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#navigation')?.classList.remove('open');$('.menu-button')?.setAttribute('aria-expanded','false');}});
Promise.all([json(document.body.dataset.page ? '/data/international.json' : '/data/home.json'),json('/player_images.json').catch(()=>({players:{}}))]).then(([data,imgs])=>{D=data;images=imgs.players;const view=document.body.dataset.page;if(view==='players')return directory();else if(view==='international')return international();else return home();}).catch(showError);
window.addEventListener('hashchange',()=>{if(D&&document.body.dataset.page==='international'){page=0;Promise.resolve(international()).catch(showError);}});
})();
