"""Transparent publication information, with working public contact routes."""
ISSUES='https://github.com/rkjat65/bleedblue/issues/new'
CONTACT='rkideas65@gmail.com'
PRIVACY_CONTACT='rkdevanda65@gmail.com'   # the address on the app store listing
UPDATED='1 October 2026'


def trust_pages(page,heading,a,checked_at):
    pages = [
      ('/about/','About Crickrida','An independent publication for researching international cricket records.',
       '<h2>Understand the game through its records</h2><p>Crickrida brings together international player careers, scorecards and statistical research for men’s and women’s cricket. Match browsing covers every official international, full members and associates. Player career totals follow recognised international status, including qualifying games against other opposition.</p><h2>How this publication works</h2><p>Crickrida is maintained through the rkjat65/bleedblue project. Data preparation and page generation are automated. Statistical explainers are computed from the same records shown in the tables; they do not represent independent human reporting or an official governing-body publication.</p><p>We publish historical records and analysis, without a live-score feed. The date a page was rebuilt is distinct from the date its underlying records were checked.</p><h2>Check our work</h2><p>'+a('/methodology/','Data methodology')+' explains definitions and gaps. '+a('/editorial-policy/','Editorial standards')+' describes how findings are presented. '+a('/contact/','Contact us')+' with a correction or publication enquiry.</p>'),
      ('/contact/','Contact Crickrida','Contact the Crickrida maintainer about data, feedback and publication enquiries.',
       '<h2>Data corrections and feedback</h2><p>Use the project’s public issue tracker to send a report to the maintainer. Include the Crickrida page URL, the figure in question and evidence supporting a correction.</p><p><a class="button primary" href="'+ISSUES+'">Open a public enquiry on GitHub ↗</a></p><p class="note">A GitHub account is required to submit an issue. Reports are public: do not include passwords, account details or sensitive personal information.</p><p>'+a('/corrections/','Prepare a structured correction report')+' before submitting it. We cannot promise a response time, but a precise report makes verification easier.</p><h2>Publication and advertising enquiries</h2><p>The same channel accepts enquiries about editorial collaboration, reuse and sponsorship. Sending an enquiry does not create a commercial agreement.</p>'),
      ('/privacy/','Privacy policy','How Crickrida handles website requests, measurement, local preferences, accounts and the mobile app.',
       '<p>This policy covers crickrida.com, including its IPL and T20 World Cup analytics, and the Crickrida mobile app. Every feature works without an account. Last updated '+UPDATED+'.</p>'
       '<h2>Website requests</h2><p>Pages are served from a server we run on Oracle Cloud. Data files for Studio and the other in-browser tools are delivered from Cloudflare R2. Each request carries connection information such as your IP address and browser details. Server logs may briefly keep the request time, address, page and browser for security and reliability; they are overwritten in normal operation. Photographs are served from this website; source and licence links take you to external services.</p>'
       '<h2>Measurement</h2><p>Google Analytics measures visits, traffic sources and page use across crickrida.com, including the IPL and T20 World Cup pages. Advertising storage and personalisation are switched off. Choose Disable analytics in the footer to stop future measurement: the site removes its Google Analytics cookies and remembers the choice in this browser, for every part of crickrida.com. Google processes usage data under its own privacy policy. Google Search Console reports search performance without a script on these pages. There are no advertising tags or newsletter sign-ups.</p>'
       '<h2>Preferences saved on your device</h2><p>Your theme, saved cricket pages, quiz best streak and analytics choice are stored in this browser’s local storage. They are not sent to us or synced between devices. Images you add to a Studio card stay in your browser and are not uploaded. Remove saved research with the notebook’s clear control, or clear this website’s data in your browser settings.</p>'
       '<h2>Accounts</h2><p>There are no visitor accounts. Sign-in exists only for site administrators, through Google. If you created an account before public accounts were retired, we keep its name, email address, sign-in provider, encrypted password and sessions until you delete it; see '+a('/account-deletion/','account deletion')+'.</p>'
       '<h2>The mobile app</h2><p>The app asks for photo-library access only when you choose to save a stat card, and shares through your phone’s share sheet. It does not access your location, contacts, microphone or camera. Session credentials for older accounts are kept in the operating system’s secure storage.</p>'
       '<h2>Corrections and contact</h2><p>The correction form prepares a report on your device. Submitting it opens the public GitHub issue tracker, where other visitors can read it; do not include private information. You can email instead. Email is handled through Gmail and kept while an enquiry is open or needed to document a correction; you can ask for its deletion.</p>'
       '<h2>Who receives data</h2><p>We do not sell personal information. Data reaches only the providers that run the service: Oracle Cloud for hosting, Cloudflare for data files, Google for Analytics and administrator sign-in, GitHub for the public issue tracker and Gmail for email. Each processes it under its own privacy terms. Public cricket records are not personal data.</p>'
       '<h2>Security and children</h2><p>Every connection uses HTTPS. No method is entirely risk-free. Crickrida is a general-audience sports site and is not directed at children under 13; if you believe a child has given us personal information, contact us so it can be removed.</p>'
       '<h2>Contact</h2><p>Privacy questions and account deletion: <a href="mailto:'+PRIVACY_CONTACT+'">'+PRIVACY_CONTACT+'</a>. Data corrections and publication enquiries: <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>.</p><p>'+a('https://policies.google.com/privacy','Google privacy policy')+' · '+a('https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement','GitHub privacy statement')+' · '+a('/terms/','Terms of use')+'</p>'),
      ('/terms/','Terms of use','Using Crickrida statistics, tools, research and attributed photographs.',
       '<p>By using crickrida.com or the Crickrida app you agree to these terms. Last updated '+UPDATED+'.</p>'
       '<h2>Using the records</h2><p>Crickrida provides free cricket records, analysis and tools for information and research. We reconcile records and explain coverage, but historical fields may be incomplete and errors can occur. Verify material claims before relying on them in journalism, wagering, financial decisions or other high-stakes uses, and use the correction channel when you find a discrepancy. Crickrida does not give betting advice.</p>'
       '<h2>Acceptable use</h2><p>Do not use Crickrida to break the law, attack or overload the service, scrape it at abusive volume, publish unlawful or harmful content, impersonate others or infringe intellectual property. We may restrict access that harms the service or its users.</p>'
       '<h2>Reuse, credits and your content</h2><p>Photographs keep their individual licences and authorship; follow the credit beside each one before reuse. Ball-by-ball data is attributed to Cricsheet. You keep the rights to charts, cards and captions you make, and you are responsible for having the right to publish what you share. A download does not grant rights to third-party material or imply endorsement.</p>'
       '<h2>Availability and liability</h2><p>The service is provided as is and as available, as far as the law allows. Features change as the data and product improve, and we do not promise uninterrupted availability or perfect accuracy. As far as the law allows, Crickrida is not liable for indirect or consequential losses from using it.</p>'
       '<h2>Independent publication</h2><p>Crickrida is independent. It is not affiliated with, endorsed by or sponsored by the ICC, any national cricket board including the BCCI, the Indian Premier League, its franchises or any player. Names and records are used to identify what is being discussed.</p>'
       '<h2>External services and contact</h2><p>Linked services, including the public issue tracker, have their own terms. Questions about these terms, partnerships or reuse go to <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>.</p><p>'+a('/privacy/','Privacy policy')+' · '+a('/contact/','Contact Crickrida')+'</p>'),
      ('/account-deletion/','Delete a Crickrida account','How to delete an account created before Crickrida retired visitor accounts.',
       '<p>Crickrida no longer offers visitor accounts: every feature is free without signing up. If you created an account before accounts were retired, you can have it and its account-linked data permanently deleted.</p>'
       '<h2>How to ask</h2><p>Email us from the address on the account. We may ask you to confirm ownership before deleting it. Older versions of the mobile app can also delete an account from More, then Account, then Delete account.</p>'
       '<p><a class="button primary" href="mailto:'+PRIVACY_CONTACT+'?subject=Crickrida%20account%20deletion%20request&amp;body=Please%20delete%20my%20Crickrida%20account%20associated%20with%20this%20email%20address.">Request account deletion</a></p>'
       '<h2>What is deleted</h2><p>Your profile, sessions and account-linked usage records. Public cricket data is not tied to your account. Files already saved to your device, or anything you shared outside Crickrida, stay under your control.</p><p>'+a('/privacy/','Privacy policy')+'</p>'),
      ('/editorial-policy/','Editorial standards & corrections','How Crickrida produces statistical analysis and corrects its records.',
       '<h2>Evidence before a conclusion</h2><p>Each statistical explainer identifies its data scope, sample and calculation. Total runs measure accumulated output; averages, scoring rates and wickets answer different questions. Cross-era comparisons are descriptive and do not automatically establish who was the greatest player.</p><h2>What is generated</h2><p>Pages and statistical observations are generated from validated data using maintained code. Explanations are published under Crickrida’s name. We do not invent interviews, personal experience or a named reviewer. Corrections are reviewed against the provided evidence and incorporated into the data pipeline.</p><h2>Missing data</h2><p>Unrecorded fields stay unavailable. We do not fill unknown balls faced with zero, infer them from rounded rates, or present a partial archive as a complete career. No dismissals and no wickets can make a rate not applicable.</p><h2>Freshness</h2><p>Career records were checked as described on each profile. The current baseline snapshot is '+checked_at+'. Match analysis reflects the dated scorecards available to the publication. A scheduled refresh attempts to update data and runs validation before publication.</p><h2>Corrections and disclosure</h2><p>'+a('/corrections/','Submit evidence for a correction')+'. Confirmed changes are recorded in the public project history. Photograph credits appear beside the image. Future paid placements will be labelled and separated from statistical tables and editorial conclusions.</p>'),
      ('/advertise/','Advertise with Crickrida','Information for future sponsors of international cricket research.',
       '<h2>International cricket, in perspective</h2><p>Crickrida serves readers exploring player records, match history, rivalries and statistical explanations. Potential future placements include clearly labelled display advertising and sponsored research collections.</p><h2>Audience figures will be measured</h2><p>We do not publish estimated reach as verified audience data. Availability, traffic figures and commercial terms will be discussed from measured results. No advertising network is active in this release.</p><h2>Reader-first placements</h2><p>Advertising must be identifiable, must not cover table controls or appear to be a statistic, and must not change the underlying data or research conclusions.</p><p>'+a('/contact/','Send an advertising enquiry')+'</p>'),
      ('/brand/','Crickrida brand assets','Download the Crickrida logo and brand artwork.',
       '<h2>The Crickrida mark</h2><div class="brand-preview"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 244 240" width="100" height="100" role="img" aria-label="Crickrida mark"><defs><mask id="crSeamBrand"><rect width="244" height="240" fill="#fff"/><path d="M103.5,137.8 L239.4,-60.0 M112.6,144.0 L248.5,-53.8" stroke="#000" stroke-width="4.5" stroke-linecap="round"/></mask></defs><path d="M0,0 L66,0 L66,98 L0,194Z" fill="currentColor"/><path d="M61.4,125.9 L95.7,76 L238.4,234.1 Q243.8,240 235.8,240 L164.4,240Z" fill="#00E5FF"/><circle cx="176" cy="42" r="39" fill="#FF2D78" mask="url(#crSeamBrand)"/></svg><strong>crickrida</strong></div><p>A K whose leg is a bat, with a ball and its seam: cricket and its numbers in one shape. The bat takes the site’s cyan and the ball its magenta, on near-black; on light backgrounds the stem turns dark. Leave at least one ball width of clear space around the mark.</p><div class="link-grid"><a href="/assets/brand/crickrida-mark.svg" download>SVG mark (light backgrounds)</a><a href="/assets/brand/crickrida-mark-on-dark.svg" download>SVG mark (dark backgrounds)</a><a href="/assets/brand/crickrida-icon.png" download>PNG app icon</a><a href="/assets/brand/crickrida-wordmark.png" download>PNG wordmark (light backgrounds)</a><a href="/assets/brand/crickrida-wordmark-dark.png" download>PNG wordmark (dark backgrounds)</a></div><h2>Our colours</h2><div class="brand-swatches"><span style="background:#00E5FF;color:#0A0A0F">Cyan · #00E5FF</span><span style="background:#FF2D78;color:#0A0A0F">Magenta · #FF2D78</span><span style="background:#0A0A0F;color:#E8E8ED">Night · #0A0A0F</span><span style="background:#111118;color:#E8E8ED">Panel · #111118</span><span style="background:#E8E8ED;color:#0A0A0F">Ink · #E8E8ED</span></div><p class="note">These assets identify Crickrida. Reuse must not imply an official partnership or endorsement.</p>'),
    ]
    for path,title,description,content in pages:
        if path=='/contact/':
            content='<h2>Email the publication</h2><p>Send corrections, feedback and publication enquiries to <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>. Include the relevant page URL and supporting evidence when reporting a data issue.</p>'+content.replace('The same channel accepts enquiries','Email also accepts enquiries')
        kind='AboutPage' if path=='/about/' else 'ContactPage' if path=='/contact/' else 'WebPage'
        page(path,title,description,heading(title,description,'THE PUBLICATION')+'<article class="panel prose">'+content+'</article>',kind)
