"""Transparent publication information, with working public contact routes."""
ISSUES='https://github.com/rkjat65/bleedblue/issues/new'
CONTACT='rkideas65@gmail.com'


def trust_pages(page,heading,a,checked_at):
    pages = [
      ('/about/','About Cricket Wicket','An independent publication for researching international cricket records.',
       '<h2>Understand the game through its records</h2><p>Cricket Wicket brings together international player careers, scorecards and statistical research for men’s and women’s cricket. Match browsing focuses on the twelve full-member national teams. Player career totals follow recognised international status, including qualifying games against other opposition.</p><h2>How this publication works</h2><p>Cricket Wicket is maintained through the rkjat65/bleedblue project. Data preparation and page generation are automated. Statistical explainers are computed from the same records shown in the tables; they do not represent independent human reporting or an official governing-body publication.</p><p>We publish historical records and analysis, without a live-score feed. The date a page was rebuilt is distinct from the date its underlying records were checked.</p><h2>Check our work</h2><p>'+a('/methodology/','Data methodology')+' explains definitions and gaps. '+a('/editorial-policy/','Editorial standards')+' describes how findings are presented. '+a('/contact/','Contact us')+' with a correction or publication enquiry.</p>'),
      ('/contact/','Contact Cricket Wicket','Contact the Cricket Wicket maintainer about data, feedback and publication enquiries.',
       '<h2>Data corrections and feedback</h2><p>Use the project’s public issue tracker to send a report to the maintainer. Include the Cricket Wicket page URL, the figure in question and evidence supporting a correction.</p><p><a class="button primary" href="'+ISSUES+'">Open a public enquiry on GitHub ↗</a></p><p class="note">A GitHub account is required to submit an issue. Reports are public: do not include passwords, account details or sensitive personal information.</p><p>'+a('/corrections/','Prepare a structured correction report')+' before submitting it. We cannot promise a response time, but a precise report makes verification easier.</p><h2>Publication and advertising enquiries</h2><p>The same channel accepts enquiries about editorial collaboration, reuse and sponsorship. Sending an enquiry does not create a commercial agreement.</p>'),
      ('/privacy/','Privacy policy','How Cricket Wicket handles local preferences, public enquiries and website requests.',
       '<h2>Website requests</h2><p>This website is hosted on GitHub Pages. When you request a page or image, the hosting service processes connection information such as your IP address and browser headers under its own privacy practices. Photographs are served from this website; following a source or licence link takes you to an external service.</p><h2>Preferences saved on your device</h2><p>Your theme preference and saved cricket pages are stored in this browser’s local storage. They are not sent to a Cricket Wicket account or synced between devices. Remove saved research through the notebook’s clear control or clear this website’s data in your browser settings.</p><h2>Forms and contact</h2><p>The correction form prepares a downloadable report on your device. Choosing to submit a report opens the public GitHub issue tracker, which has its own terms and privacy policy. Information submitted there can be read by other visitors. Do not include private or sensitive information.</p><h2>Measurement and advertising</h2><p>Google Search Console provides search-performance and indexing reports without requiring a tracking script on these pages. This release does not load Google Analytics, advertising tags or a newsletter sign-up service. If those services are introduced, this policy and relevant consent controls will be updated before they are enabled.</p><h2>External services and your choices</h2><p>Links to Wikimedia Commons, Cricsheet, GitHub and IPL Analytics leave this publication. Those services process requests according to their own policies. You can use the public contact channel for questions about this policy.</p><p>'+a('https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement','GitHub privacy statement')+' · '+a('/contact/','Contact the maintainer')+'</p>'),
      ('/terms/','Terms of use','Using Cricket Wicket statistics, research and attributed photographs.',
       '<h2>Using the records</h2><p>Cricket Wicket is provided for general information and research. We work to reconcile records and explain coverage, but historical fields may be incomplete and errors may occur. Verify material claims against the supporting records and use the correction channel when you find a discrepancy.</p><h2>Reuse and credits</h2><p>Photographs retain their individual licences and authorship. Follow the credit and licence beside each photograph before reusing it. Ball-by-ball data is attributed to Cricsheet. A downloadable chart or table does not grant rights to unrelated third-party material or imply endorsement.</p><h2>Independent publication</h2><p>Cricket Wicket is not an official cricket board, governing body or player representative. Names and records are used to identify the subjects being discussed.</p><h2>External services</h2><p>Linked services, including the public issue tracker, have their own terms. Contact the maintainer for a proposed commercial partnership or reuse that needs clarification.</p><p>'+a('/contact/','Contact Cricket Wicket')+'</p>'),
      ('/editorial-policy/','Editorial standards & corrections','How Cricket Wicket produces statistical analysis and corrects its records.',
       '<h2>Evidence before a conclusion</h2><p>Each statistical explainer identifies its data scope, sample and calculation. Total runs measure accumulated output; averages, scoring rates and wickets answer different questions. Cross-era comparisons are descriptive and do not automatically establish who was the greatest player.</p><h2>What is generated</h2><p>Pages and statistical observations are generated from validated data using maintained code. Explanations are published under Cricket Wicket’s name. We do not invent interviews, personal experience or a named reviewer. Corrections are reviewed against the provided evidence and incorporated into the data pipeline.</p><h2>Missing data</h2><p>Unrecorded fields stay unavailable. We do not fill unknown balls faced with zero, infer them from rounded rates, or present a partial archive as a complete career. No dismissals and no wickets can make a rate not applicable.</p><h2>Freshness</h2><p>Career records were checked as described on each profile. The current baseline snapshot is '+checked_at+'. Match analysis reflects the dated scorecards available to the publication. A scheduled refresh attempts to update data and runs validation before publication.</p><h2>Corrections and disclosure</h2><p>'+a('/corrections/','Submit evidence for a correction')+'. Confirmed changes are recorded in the public project history. Photograph credits appear beside the image. Future paid placements will be labelled and separated from statistical tables and editorial conclusions.</p>'),
      ('/advertise/','Advertise with Cricket Wicket','Information for future sponsors of international cricket research.',
       '<h2>International cricket, in perspective</h2><p>Cricket Wicket serves readers exploring player records, match history, rivalries and statistical explanations. Potential future placements include clearly labelled display advertising and sponsored research collections.</p><h2>Audience figures will be measured</h2><p>We do not publish estimated reach as verified audience data. Availability, traffic figures and commercial terms will be discussed from measured results. No advertising network is active in this release.</p><h2>Reader-first placements</h2><p>Advertising must be identifiable, must not cover table controls or appear to be a statistic, and must not change the underlying data or research conclusions.</p><p>'+a('/contact/','Send an advertising enquiry')+'</p>'),
      ('/brand/','Cricket Wicket brand assets','Download the Cricket Wicket logo and brand artwork.',
       '<h2>A mark for the international game</h2><div class="brand-preview"><img src="/logo.svg" width="100" height="100" alt="Cricket Wicket: blue square with white wickets and a gold ball"><strong>CRICKET WICKET<span>.</span></strong></div><p>The mark combines a blue field, white cricket wickets and a gold ball. Keep the proportions and leave clear space around it.</p><div class="link-grid"><a href="/logo.svg" download>SVG logo</a><a href="/assets/brand/cricket-wicket-icon.png" download>High-resolution PNG icon</a><a href="/assets/brand/cricket-wicket-wordmark.png" download>Transparent PNG wordmark</a></div><h2>Our colours</h2><div class="brand-swatches"><span style="background:#205ed2;color:white">Blue · #205ED2</span><span style="background:#10233f;color:white">Navy · #10233F</span><span style="background:#efb75b;color:#10233f">Gold · #EFB75B</span></div><p class="note">These assets identify Cricket Wicket. Reuse must not imply an official partnership or endorsement.</p>'),
    ]
    for path,title,description,content in pages:
        if path=='/contact/':
            content='<h2>Email the publication</h2><p>Send corrections, feedback and publication enquiries to <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>. Include the relevant page URL and supporting evidence when reporting a data issue.</p>'+content.replace('The same channel accepts enquiries','Email also accepts enquiries')
        if path=='/privacy/':
            content=content.replace('Information submitted there can be read by other visitors.', 'Information submitted there can be read by other visitors. You can instead email '+CONTACT+'. Email enquiries are processed through Gmail, and the maintainer uses the information to respond and investigate the request. Relevant correspondence may be retained while the enquiry is being handled or needed to document a correction; you can request deletion by email.')
        kind='AboutPage' if path=='/about/' else 'ContactPage' if path=='/contact/' else 'WebPage'
        page(path,title,description,heading(title,description,'THE PUBLICATION')+'<article class="panel prose">'+content+'</article>',kind)
