"""Crawlable introduction and progressive data/visual controls for Studio."""
def studio_markup(link):
    templates=[('player','Player record','Career figures by format'),('compare','Player comparison','Compare two international careers'),('record','Career leaderboard','Find qualified record holders'),('timeline','Player timeline','Every recorded year'),('batting','Batting explorer','Opponents, venues and positions'),('bowling','Bowling explorer','Wickets and bowling rates'),('team','Team form','Recent results and winners'),('venue','Venue record','Explore a ground across formats'),('year','Year recap','Rank a selected year'),('match','Match picture','Export a scorecard share card'),('custom','Custom analysis','Choose dataset, metric and grouping')]
    cards=''.join(f'<button class="template-card" data-template="{key}"><strong>{name}</strong><small>{desc}</small></button>' for key,name,desc in templates)
    def select(ident,label,items):
        return f'<label>{label}<select id="{ident}">'+''.join(f'<option value="{value}">{text}</option>' for value,text in items)+'</select></label>'
    format_control=select('studio-format','Format',[('','All formats'),('Test','Test'),('ODI','ODI'),('T20I','T20I')])
    gender_control=select('studio-gender','Gender',[('Men','Men'),('Women','Women')])
    return f'''<div class="studio-shell"><section class="studio-mast"><div><span class="eyebrow">CRICKET WICKET · SOCIAL & ANALYSIS STUDIO</span><h1>Your question. Your chart. Your cricket story.</h1><p>Query international records, shape the visual and export it for your audience. Start with a template or build your own analysis.</p></div><p>Men & women<br>Tests · ODIs · T20Is<br>Cricsheet data</p></section>
    <section aria-label="Analysis templates"><div class="studio-section-title"><h2>Start with a question</h2></div><div class="template-grid">{cards}</div></section>
    <section class="studio-workspace"><aside class="studio-config"><h2>Choose your data</h2><p id="studio-status" class="studio-status" role="status">Loading international datasets…</p><form id="studio-form">
    {select('studio-dataset','Dataset',[('careers','Official careers'),('batting','Batting innings'),('bowling','Bowling innings'),('matches','Match archive')])}
    <div class="control-pair">{gender_control}{format_control}</div>
    <label id="player-one-field">Player<input id="player-one" list="studio-players" placeholder="All players"></label><label id="player-two-field" hidden>Compare with<input id="player-two" list="studio-players" placeholder="Choose another player"></label><datalist id="studio-players"></datalist>
    <label>Team<select id="studio-team"></select></label><label id="opponent-field">Opponent<select id="studio-opponent"></select></label><label id="venue-field">Venue<select id="studio-venue"></select></label>
    <div class="control-pair" id="year-fields"><label>From year<input id="studio-from" type="number" min="1877" max="2100"></label><label>To year<input id="studio-to" type="number" min="1877" max="2100"></label></div>
    <label id="position-field">Batting position<select id="studio-position"><option value="">All positions</option>{''.join(f'<option>{i}</option>' for i in range(1,12))}</select></label>
    <label id="match-field" hidden>Match<select id="studio-match"></select></label>
    <div class="control-pair"><label>Metric<select id="studio-metric"></select></label><label>Group by<select id="studio-group"></select></label></div>
    <div class="control-pair"><label>Minimum matches<input id="studio-minimum" type="number" min="0" max="100000" value="0"></label><label>Result limit<input id="studio-limit" type="number" min="1" max="100" value="10"></label></div>
    <button type="submit" id="build-visual" class="primary wide">Run analysis</button></form>
    <details><summary>Query and dataset version</summary><p id="lake-version" class="note"></p><pre id="sql" class="studio-query"></pre></details>
    </aside><div class="studio-preview-column"><section class="studio-design panel"><h2>Make it yours</h2><div class="design-controls">
    {select('design-type','Visual',[('bar','Horizontal bars'),('column','Columns'),('line','Line chart'),('table','Data table'),('number','Headline number'),('card','Match picture card')])}
    {select('design-size','Canvas',[('landscape','Landscape · 1200 × 675'),('square','Square · 1080 × 1080'),('portrait','Portrait · 1080 × 1920')])}
    {select('design-theme','Theme',[('light','Cricket Wicket light'),('navy','Cricket Wicket navy'),('paper','Editorial paper')])}
    <label>Accent<input type="color" id="design-accent" value="#1d4ed8"></label><label>Title<input id="design-title" maxlength="100" placeholder="Automatic title"></label><label>Your subtitle<input id="design-subtitle" maxlength="160" placeholder="Add your commentary"></label>
    {select('design-labels','Value labels',[('on','Show exact values'),('off','Hide values')])}
    </div><details class="card-photo-editor" open><summary>Card photos</summary><p class="note">Use a player photo or add a JPEG, PNG or WebP (up to 12 MB). Your images stay in this tab and are included in PNG/SVG downloads only. Changing the player clears their local photo. Saved designs and shared links do not include uploaded images.</p><div class="card-photo-grid">
    {''.join(f'<section id="card-photo-{i}" class="card-photo-slot" '+('hidden' if i else '')+f'><h3 data-photo-name>{"Card image" if i==0 else "Second player"}</h3><div class="card-photo-preview"><img hidden width="72" height="88" alt=""><span data-photo-credit></span></div><label>Photo source {i+1}<select aria-label="Photo source {i+1}"><option value="auto">Automatic player photo</option><option value="upload">My image</option><option value="none">No photo</option></select></label><label>Add card image {i+1}<input type="file" accept="image/jpeg,image/png,image/webp" aria-label="Add card image {i+1}"></label><button type="button" data-photo-remove>Remove photo {i+1}</button><p class="note" data-photo-status role="status">Choose a player, or add your own card image.</p></section>' for i in range(2))}
    </div></details></section>
    <div class="export-actions"><button id="download-card" disabled>Download PNG</button><button id="full-preview" disabled>Full-size preview</button><button id="download-svg" disabled>Download SVG</button><button id="download-data" disabled>Download CSV</button><button id="copy-link">Copy setup link</button><button id="save-design">Save design</button><button id="load-design">Open saved design</button><button id="reset-design">Reset styling</button></div>
    <div id="export-frame" class="export-frame"><div id="story-card" aria-live="polite"><p>Choose data and run an analysis to preview your story.</p></div></div><p id="preview-note" class="preview-note">Exact values and sample sizes remain available below every visual. Colours, titles and layout do not change the underlying records.</p>
    <section class="panel"><h2>Data behind your visual</h2><div id="studio-result-table"></div></section></div></section>
    <section class="panel studio-method"><h2>International cricket, ready to explore</h2><div class="grid three"><div><h3>Official careers</h3><p>Compare recognised career records by format. Career figures include all qualifying international opposition.</p></div><div><h3>Available scorecards</h3><p>Filter recorded innings by player, team, opposition, venue and year. Unknown values remain unknown.</p></div><div><h3>Your visual identity</h3><p>Adjust chart type, colours, text and social dimensions. Save your setup on this device or share a reproducible link.</p></div></div><p>{link('/data-coverage/','See dataset coverage')} · {link('/methodology/','Read statistical definitions')} · {link('/research/','Browse player research')}</p></section></div>'''
