"""Markup for the data-backed Cricket Wicket content studio."""

def studio_markup(link):
    templates=[('player','Player stats','Career record by format'),('match','Match summary','Result, teams and venue'),('compare','Comparison','Two careers, one card'),('record','Record card','A leaderboard-ready fact'),('timeline','Career timeline','Runs or wickets by year'),('team','Team form','Recent international results'),('venue','Venue record','Formats, matches and winners'),('year','Year recap','Leading performers in a year')]
    cards=''.join(f'<button class="template-card" data-template="{key}"><span>{i+1:02}</span><strong>{name}</strong><small>{desc}</small></button>' for i,(key,name,desc) in enumerate(templates))
    return f'''<div class="studio-shell"><section class="studio-mast"><div><span class="eyebrow">CRICKET WICKET CREATOR</span><h1>Turn international cricket data into publishable stories.</h1><p>Choose a format, find the exact record, and export a branded visual built from the same verified data as the site.</p></div><div class="studio-mast-stat"><strong>8</strong><span>editorial templates</span><strong>3</strong><span>international formats</span></div></section>
    <section><div class="studio-section-title"><div><span>01</span><h2>Choose a template</h2></div><p>Each template changes the available data controls and visual treatment.</p></div><div class="template-grid">{cards}</div></section>
    <section class="studio-workspace"><aside class="studio-config"><div class="studio-section-title"><div><span>02</span><h2>Configure data</h2></div></div><div id="studio-status" class="studio-status" aria-live="polite">Loading the international data catalogue…</div>
    <label id="player-one-field">Player<input id="player-one" list="studio-players" placeholder="Search international player"></label><label id="player-two-field">Compare with<input id="player-two" list="studio-players" placeholder="Search second player"></label><datalist id="studio-players"></datalist>
    <label id="team-field">Team<select id="studio-team"></select></label><label id="venue-field">Venue<select id="studio-venue"></select></label><label id="match-field">Match<select id="studio-match"></select></label>
    <div class="control-pair"><label>Format<select id="studio-format"><option value="">All formats</option><option>Test</option><option>ODI</option><option>T20I</option></select></label><label>Gender<select id="studio-gender"><option>Men</option><option>Women</option></select></label></div>
    <div class="control-pair"><label id="year-field">Year<select id="studio-year"></select></label><label>Metric<select id="studio-metric"><option value="runs">Runs</option><option value="wickets">Wickets</option><option value="matches">Matches</option><option value="hundreds">Centuries</option></select></label></div>
    <label>Output format<div class="segmented"><button data-ratio="landscape">Landscape</button><button data-ratio="square">Square</button><button data-ratio="portrait">Portrait</button></div></label><button id="build-visual" class="primary wide">Refresh visual</button><details><summary>View data query</summary><pre id="sql" class="studio-query"></pre></details></aside>
    <div class="studio-preview-column"><div class="studio-section-title"><div><span>03</span><h2>Live preview</h2></div><div class="export-actions"><button id="download-card">Download PNG</button><button id="download-data">Download CSV</button><button id="copy-link">Copy setup link</button></div></div>
    <div id="export-frame" class="export-frame landscape"><article id="story-card" class="story-card"><header><div class="story-brand"><img src="/logo.svg" alt=""><strong>CRICKET WICKET</strong></div><span id="story-kicker">INTERNATIONAL CRICKET</span></header><div id="story-content" class="story-content"><div class="story-loading">Building your cricket story…</div></div><footer><span>cricket.rkjat.in</span><span>Data-backed cricket stories</span></footer></article></div><p class="preview-note">Exports are rendered at high resolution. Career and scorecard archive scopes remain clearly labelled.</p></div></section>
    <section class="panel studio-method"><h2>A creator built on the complete publication</h2><div class="grid three"><div><strong>Official careers</strong><p>Recognized international career records, with Tests, ODIs and T20Is kept distinct.</p></div><div><strong>Match archive</strong><p>Results and available scorecards for the twelve full-member national teams.</p></div><div><strong>Transparent scope</strong><p>Every visual states whether it uses complete career records or available scorecards.</p></div></div><p>{link('/methodology/','Read data definitions and coverage')}</p></section></div>'''
