const $=s=>document.querySelector(s),LAKE=(window.CRICKET_WICKET_LAKE||'https://pub-2deb6471d5df4274810ac4497fdf3ab2.r2.dev/').replace(/\/?$/,'/');let db,conn,template='player',rows=[];
const files={careers:'careers.parquet',matches:'matches.parquet',innings:'batting_innings.parquet'},esc=x=>{let d=document.createElement('div');d.textContent=x??'—';return d.innerHTML},num=x=>x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:2}),q=x=>"'"+String(x).replaceAll("'","''")+"'";
async function query(sql){$('#sql').textContent=sql;return (await conn.query(sql)).toArray().map(r=>({...r}))}
async function boot(){try{window.duckdb=await import('https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.33.1-dev57.0/+esm');let b=await duckdb.selectBundle(duckdb.getJsDelivrBundles()),w=await duckdb.createWorker(b.mainWorker);db=new duckdb.AsyncDuckDB(new duckdb.ConsoleLogger(),w);await db.instantiate(b.mainModule,b.pthreadWorker);conn=await db.connect();await hydrate();bind();selectTemplate('player');$('#studio-status').textContent='Verified international datasets ready'}catch(e){$('#studio-status').textContent='Data engine error: '+e.message}}
async function hydrate(){let careers=`read_parquet('${LAKE+files.careers}')`,matches=`read_parquet('${LAKE+files.matches}')`;let players=await query(`SELECT DISTINCT player FROM ${careers} ORDER BY player`),teams=await query(`SELECT team FROM (SELECT team_1 team FROM ${matches} UNION SELECT team_2 FROM ${matches}) ORDER BY team`),venues=await query(`SELECT venue, count(*) n FROM ${matches} WHERE venue IS NOT NULL GROUP BY 1 ORDER BY n DESC`),years=await query(`SELECT DISTINCT year FROM ${matches} ORDER BY year DESC`),games=await query(`SELECT match_id,date,team_1,team_2,format FROM ${matches} ORDER BY date DESC LIMIT 500`);$('#studio-players').innerHTML=players.map(x=>`<option value="${esc(x.player)}">`).join('');$('#player-one').value=players.find(x=>x.player==='Sachin Tendulkar')?.player||players[0]?.player||'';$('#player-two').value=players.find(x=>x.player==='Virat Kohli')?.player||players[1]?.player||'';$('#studio-team').innerHTML=teams.map(x=>`<option>${esc(x.team)}</option>`).join('');$('#studio-venue').innerHTML=venues.map(x=>`<option>${esc(x.venue)}</option>`).join('');$('#studio-year').innerHTML=years.map(x=>`<option>${x.year}</option>`).join('');$('#studio-match').innerHTML=games.map(x=>`<option value="${x.match_id}">${x.date} · ${esc(x.team_1)} v ${esc(x.team_2)} · ${x.format}</option>`).join('')}
function bind(){document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>selectTemplate(b.dataset.template));document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=e=>{e.preventDefault();document.querySelectorAll('[data-ratio]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#export-frame').className='export-frame '+b.dataset.ratio});document.querySelector('[data-ratio="landscape"]').classList.add('active');$('#build-visual').onclick=render;['studio-format','studio-gender','studio-metric','studio-team','studio-venue','studio-year','studio-match'].forEach(id=>$('#'+id).onchange=render);$('#player-one').onchange=render;$('#player-two').onchange=render;$('#download-data').onclick=csv;$('#copy-link').onclick=share;$('#download-card').onclick=png}
function selectTemplate(t){template=t;document.querySelectorAll('[data-template]').forEach(b=>b.classList.toggle('active',b.dataset.template===t));let show=(id,on)=>$('#'+id).hidden=!on;show('player-one-field',['player','compare','record','timeline'].includes(t));show('player-two-field',t==='compare');show('team-field',t==='team');show('venue-field',t==='venue');show('match-field',t==='match');show('year-field',t==='year');render()}
function filters(alias=''){let a=alias?alias+'.':'';return `${$('#studio-format').value?` AND ${a}format=${q($('#studio-format').value)}`:''} AND ${a}gender=${q($('#studio-gender').value)}`}
async function render(){if(!conn)return;$('#studio-status').textContent='Querying the selected records…';try{let C=`read_parquet('${LAKE+files.careers}')`,M=`read_parquet('${LAKE+files.matches}')`,I=`read_parquet('${LAKE+files.innings}')`,p=$('#player-one').value,p2=$('#player-two').value,metric=$('#studio-metric').value,sql,title,sub,kicker='OFFICIAL INTERNATIONAL CAREER';
if(template==='player'||template==='record'){sql=`SELECT * FROM ${C} WHERE player=${q(p)}${filters()} ORDER BY format`;rows=await query(sql);let total=rows.reduce((s,r)=>s+Number(r[metric]||0),0);title=p;sub=rows.map(r=>r.format).join(' · ')||'No matching format';let stats=$('#studio-format').value&&rows[0]?[['Matches',rows[0].matches],['Average',rows[0].avg],['Strike rate',rows[0].sr],['Wickets',rows[0].wickets]]:[['Matches',rows.reduce((s,r)=>s+Number(r.matches||0),0)],['Innings',rows.reduce((s,r)=>s+Number(r.innings||0),0)],['Centuries',rows.reduce((s,r)=>s+Number(r.hundreds||0),0)],['Wickets',rows.reduce((s,r)=>s+Number(r.wickets||0),0)]];story(title,sub,metric==='runs'?total:num(total),metric,stats,kicker)}
else if(template==='compare'){sql=`SELECT * FROM ${C} WHERE player IN (${q(p)},${q(p2)})${filters()} ORDER BY player,format`;rows=await query(sql);let total=n=>rows.filter(r=>r.player===n).reduce((s,r)=>s+Number(r[metric]||0),0);versus(p,p2,total(p),total(p2),metric,'OFFICIAL CAREER COMPARISON')}
else if(template==='timeline'){sql=`SELECT year, sum(runs) value FROM ${I} WHERE player=${q(p)}${filters()} GROUP BY 1 ORDER BY 1`;rows=await query(sql);bars(p,'Career timeline',rows.map(r=>({label:r.year,value:r.value})),'AVAILABLE SCORECARD ARCHIVE')}
else if(template==='team'){let team=$('#studio-team').value;sql=`SELECT date,team_1,team_2,winner,format,venue FROM ${M} WHERE (team_1=${q(team)} OR team_2=${q(team)})${filters()} ORDER BY date DESC LIMIT 10`;rows=await query(sql);let wins=rows.filter(r=>r.winner===team).length;story(team,'Last 10 recorded internationals',wins,'wins',[['Matches',rows.length],['Wins',wins],['Losses',rows.filter(r=>r.winner&&r.winner!==team).length],['Other',rows.filter(r=>!r.winner).length]],'RECENT TEAM FORM')}
else if(template==='venue'){let v=$('#studio-venue').value;sql=`SELECT format,count(*) matches,count(DISTINCT winner) winners FROM ${M} WHERE venue=${q(v)}${filters()} GROUP BY 1 ORDER BY matches DESC`;rows=await query(sql);bars(v,'International matches by format',rows.map(r=>({label:r.format,value:r.matches})),'VENUE RECORD')}
else if(template==='year'){let y=$('#studio-year').value;sql=`SELECT player,sum(runs) value,count(*) innings FROM ${I} WHERE year=${Number(y)}${filters()} GROUP BY 1 ORDER BY value DESC LIMIT 7`;rows=await query(sql);bars(y+' season','Leading run scorers',rows.map(r=>({label:r.player,value:r.value})),'YEAR IN REVIEW')}
else{let id=$('#studio-match').value;sql=`SELECT * FROM ${M} WHERE match_id=${q(id)}`;rows=await query(sql);let r=rows[0]||{};versus(r.team_1||'Team 1',r.team_2||'Team 2',r.winner===r.team_1?'WIN':'',r.winner===r.team_2?'WIN':'','',`${r.date||''} · ${r.format||''} · ${r.venue||''}`)}
$('#studio-status').textContent=`${rows.length} source row${rows.length===1?'':'s'} · live preview updated`;save()}catch(e){$('#studio-status').textContent='Query error: '+e.message}}
function story(title,sub,big,unit,stats,kicker){$('#story-kicker').textContent=kicker;$('#story-content').innerHTML=`<div class="story-subtitle">${esc(sub)}</div><h2 class="story-title">${esc(title)}</h2><div><span class="story-number">${num(big)}</span> <b>${esc(unit).toUpperCase()}</b></div><div class="story-stats">${stats.map(([l,v])=>`<div class="story-stat"><strong>${num(v)}</strong><span>${esc(l)}</span></div>`).join('')}</div>`}
function versus(a,b,av,bv,metric,kicker){$('#story-kicker').textContent=kicker;$('#story-content').innerHTML=`<div class="story-versus"><div><b>${esc(metric).toUpperCase()}</b><h2 class="story-title">${esc(a)}</h2><strong>${num(av)}</strong></div><span>VERSUS</span><div><b>${esc(metric).toUpperCase()}</b><h2 class="story-title">${esc(b)}</h2><strong>${num(bv)}</strong></div></div>`}
function bars(title,sub,data,kicker){let max=Math.max(...data.map(x=>Number(x.value)||0),1);$('#story-kicker').textContent=kicker;$('#story-content').innerHTML=`<div class="story-subtitle">${esc(sub)}</div><h2 class="story-title">${esc(title)}</h2><div class="story-bars">${data.slice(0,8).map(x=>`<div class="story-bar"><span>${esc(x.label)}</span><i style="width:${Math.max(3,Number(x.value)/max*100)}%"></i><strong>${num(x.value)}</strong></div>`).join('')}</div>`}
function csv(){if(!rows.length)return;let keys=Object.keys(rows[0]),text=keys.join(',')+'\n'+rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='cricket-wicket-'+template+'.csv';a.click();URL.revokeObjectURL(a.href)}
async function png(){let canvas=await html2canvas($('#story-card'),{scale:2,backgroundColor:null,useCORS:true}),a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='cricket-wicket-'+template+'.png';a.click()}
function save(){let state={template,player:$('#player-one').value,compare:$('#player-two').value,format:$('#studio-format').value,gender:$('#studio-gender').value,team:$('#studio-team').value,venue:$('#studio-venue').value,year:$('#studio-year').value,metric:$('#studio-metric').value};history.replaceState(null,'','#'+btoa(unescape(encodeURIComponent(JSON.stringify(state)))))}async function share(){await navigator.clipboard.writeText(location.href);$('#studio-status').textContent='Shareable Studio setup copied'}
addEventListener('DOMContentLoaded',boot);


